"use client";
import { FunctionComponent } from "react";
import Topbar from "../components/Topbar";
import Footer from "../components/Footer";

const TermServices: FunctionComponent = () => {
  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans">
        <Topbar />
      {/* Main content */}
      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <h1 className="text-3xl sm:text-4xl font-bold text-center mb-8">Terms and Conditions</h1>

        <article className="space-y-6 text-sm sm:text-base leading-relaxed">
          <p>
            Welcome to GitDocify ("Services"), a web-based platform dedicated to helping users generate
            structured code documentation for their code repositories. The Services are offered by the
            owner(s) of GitDocify, an unincorporated entity ("Provider" or "we"). By accessing or using our
            Services, you agree to comply with these Terms and Conditions ("Terms"). Please review them
            thoroughly before using the Services.
          </p>

          <p className="font-semibold text-red-600">IF YOU DO NOT AGREE WITH THESE TERMS, YOU ARE NOT AUTHORIZED TO USE THE SERVICES AND MUST CEASE USE IMMEDIATELY.</p>

          <p>
            The Services are intended for users aged 13 or older. If you are a minor (under the age of 18) in the
            jurisdiction where you reside, you must obtain parental or guardian consent and be directly supervised
            while using the Services. If you are a minor, your parent or guardian must read and accept these Terms
            on your behalf before you can use the Services. We recommend that you keep a copy of these Terms for your records.
          </p>

          <section>
            <h2 className="text-xl font-semibold mt-4">1. SERVICE AVAILABILITY &amp; LIABILITY</h2>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>While we strive to make the Platform available at all times, we do not guarantee that it will be uninterrupted or error-free.</li>
              <li>We do not assume responsibility for any inaccuracies or errors in the content generated by our platform.</li>
              <li>Our platform is provided "as is" and we make no guarantees regarding its functionality or availability.</li>
              <li>In no event shall the Company be liable for any damages resulting from the use of the Platform.</li>
              <li>We reserve the right to update or discontinue our platform at any time without notice.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">2. INTELLECTUAL PROPERTY RIGHTS</h2>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>
                All content, features, and functionality available through the "GitDocify" platform, including but not limited to text,
                graphics, logos, images, software, and data compilations (collectively, "Platform Content"), are the exclusive property of
                GitDocify, its licensors, or other content providers, and are protected by applicable copyright, trademark, and other
                intellectual property laws.
              </li>
              <li>
                You may not copy, reproduce, distribute, display, transmit, modify, create derivative works from, or otherwise use any
                Platform Content without the prior written consent of GitDocify, except as permitted by applicable law or explicitly
                authorized by us.
              </li>
              <li>
                All trademarks, service marks, and trade names used on the platform (including "GitDocify") are the property of GitDocify
                or their respective owners. Unauthorized use of any of these marks is strictly prohibited.
              </li>
              <li>
                GitDocify may incorporate open-source software components that is subject to its own license terms, which may include
                licenses such as the MIT license. By using the platform, you acknowledge that your use of any such third-party components
                is governed by the applicable third-party license(s), and you agree to comply with those terms where relevant.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">3. PRIVACY POLICY</h2>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>We take the protection of our users' personal information very seriously.</li>
              <li>Our privacy policy, which can be found on our website, explains how we collect, use, protect and disclose personal information.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">4. FREE TRIAL AND SUBSCRIPTIONS</h2>

            <div className="mt-3 space-y-3">
              <div>
                <strong>Free Trial</strong>
                <p className="mt-2">We offer a free trial that allows you to generate one (1) README with limited features. This trial does not include access to certain premium functionalities (such as private repository support, premium README sections, or copy/export options). Availability of the free trial and features provided may be subject to change at any moment.</p>
                <p className="mt-2">Once you have reached your free trial limit or wish to access additional features, you may upgrade to one of our paid subscription plans.</p>
              </div>

              <div>
                <strong>Subscription Plans</strong>
                <ul className="list-disc ml-6 mt-2 space-y-2">
                  <li>Monthly Plan: $14.95 per month, providing: Full access to private repositories, Premium README features, Up to 50 generations per month, and Copy/export options.</li>
                  <li>Lifetime Plan: $54.99 (one-time payment), providing: Full access to private repositories, Premium README features, Up to 50 generations per month, Copy/export options, and Access to future feature updates at no additional charge.</li>
                </ul>
              </div>

              <div>
                <strong>Payment Options</strong>
                <p className="mt-2">We accept various payment methods, including credit/debit cards and mobile payment options such as Apple Pay and Google Pay. All payments are processed securely through trusted third-party providers.</p>
              </div>

              <div>
                <strong>Auto-Renewal</strong>
                <p className="mt-2">By subscribing to a Monthly Plan, you agree to pay the subscription fees indicated at the time of purchase. Your subscription will automatically renew at the end of each billing cycle unless you cancel before the renewal date. You may manage your subscription and disable auto-renewal at any time via your account settings. The Lifetime Plan is a one-time payment and does not renew.</p>
              </div>

              <div>
                <strong>Cancellation and Refunds</strong>
                <p className="mt-2">You may cancel your Monthly Plan at any time through your account settings. Cancellations take effect at the end of the current billing cycle. No refunds will be provided for any remaining portion of the billing period following cancellation. All purchases, including the Lifetime Plan, are non-refundable once completed.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">5. DISCLAIMER OF WARRANTIES</h2>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>Services Provided "As Is": The Services are provided on an "as is" and "as available" basis. GitDocify and its licensors make no representations or warranties of any kind—express, implied, statutory, or otherwise—regarding the operation or availability of the Services, or the accuracy, reliability, completeness, or suitability of the information, content, materials, or products included on or generated by the platform.</li>
              <li>User Assumption of Risk: You expressly agree that your use of the Services is at your sole risk. To the fullest extent permissible under applicable law, GitDocify disclaims all warranties, whether express, implied, or statutory, including but not limited to any warranties of merchantability, fitness for a particular purpose, non-infringement, and error-free operation.</li>
              <li>No Guarantee of Uninterrupted or Error-Free Service: GitDocify does not guarantee that the Services will be secure, uninterrupted, error-free, or available at all times. We reserve the right to modify, suspend, or discontinue any aspect of the Services at any time, without notice or liability.</li>
              <li>Content and Accuracy: Any content generated, provided, or displayed via the Services is for informational purposes only. GitDocify does not warrant or guarantee the correctness, completeness, or usefulness of such content. You are solely responsible for verifying and evaluating the accuracy and suitability of any information or results obtained through the Services.</li>
              <li>Jurisdictional Limitations: Because some jurisdictions do not allow the exclusion of certain warranties, the above exclusions may not apply to you. In such jurisdictions, GitDocify's warranties shall be limited to the greatest extent permitted by law.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">6. LIMITATION OF LIABILITY</h2>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>To the fullest extent permitted by law, GitDocify and its licensors shall not be liable for any direct, indirect, incidental, punitive, or consequential damages, including but not limited to, damages for loss of profits, goodwill, data, or other intangible losses, arising out of or in connection with your use of the Services or any purchase, even if we have been advised of the possibility of such damages.</li>
              <li>In no event shall our total liability to you for all damages exceed the amount you paid, if any, for accessing the Services or purchases during the six (6) months preceding the event giving rise to the claim.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">7. CHANGES TO TERMS</h2>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>GitDocify reserves the right to modify or revise these Terms at any time, for any reason. The determination of what constitutes a material change will be at the sole discretion of GitDocify.</li>
              <li>By continuing to use the Services after such changes, you accept and agree to the updated Terms. If you do not agree to the revised Terms, you must cease using the Services immediately.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">8. CONTACT US</h2>
            <p>If you have any questions or concerns regarding these terms of service, please contact us at <a className="text-blue-600 underline" href="mailto:support@gitdocify.com">support@gitdocify.com</a>.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mt-4">USER POLICY</h2>
            <ul className="list-disc ml-6 mt-3 space-y-2">
              <li>
                <strong>Permissible Use:</strong> The "GitDocify" platform is provided for lawful and authorized use only. By accessing or using the Services, you agree to use the platform solely for legitimate, non-commercial, and recreational purposes, unless otherwise expressly permitted in writing by GitDocify.
              </li>
              <li>
                <strong>Prohibited Activities:</strong> You must not use the platform for any illegal, fraudulent, or unauthorized purposes, including but not limited to misuse, exploitation, or manipulation of the platform's features. We reserve the right to suspend, restrict, or terminate access to any account found to be in violation of these terms.
              </li>
              <li>
                <strong>Responsibility for Submitted Code and Content</strong>
              </li>
              <li>
                You agree that you are solely responsible for any code, data, or other content you submit to or process through GitDocify. This includes ensuring you have all necessary permissions, licenses, or rights to use, upload, or modify such content, particularly if it is proprietary or protected (e.g., company-owned or confidential).
              </li>
              <li>
                By using GitDocify, you represent and warrant that your submission or processing of any code or content does not infringe upon any third party's rights, including intellectual property, trade secrets, or confidentiality obligations.
              </li>
              <li>
                GitDocify disclaims any liability arising from users' unauthorized use of code or content protected by law. We do not monitor or verify the ownership or legality of any submitted materials; you assume full responsibility for any claims, disputes, or damages resulting from your misuse or unauthorized use of such content.
              </li>
              <li>
                <strong>Enforcement:</strong> We reserve the right to investigate and take appropriate action—such as suspending, restricting, or terminating your account—if we believe you have violated this User Policy or any other applicable terms.
              </li>
            </ul>
          </section>
        </article>

      </main>
        <Footer />
    </div>
  );
};

export default TermServices;
