import { FaGithub } from "react-icons/fa";
import { FiZap, FiBookOpen } from "react-icons/fi";

export const featureCards = [
  {
    icon: FaGithub,
    bg: "#DBEAFE",
    title: "Compatible with All Public GitHub Repos",
    desc: "Connect and generate documentation for any public repository with ease.",
  },
  {
    icon: FiZap,
    bg: "#fff7ed",
    title: "Lightning-Fast README Generation",
    desc: "Get professional documentation in seconds using advanced AI technology.",
  },
  {
    icon: FiBookOpen,
    bg: "#eefaf1",
    title: "Full Documentation Coming",
    desc: "Complete code documentation features are in development and coming to you soon.",
  },
];

export const roadmapPhases = [
  {
    title: "Phase 1: README Generation",
    desc: "Available now – Create professional README files instantly.",
  },
  {
    title: "Phase 2: Full Code Documentation",
    desc: "Available now – Comprehensive documentation for classes, functions, and more.",
  },
  {
    title: "Phase 3: Apply & Download",
    desc: "Available now – Apply automatic and Download files instantly.",
  },
  {
    title: "Phase 4: Repositories Types",
    desc: "Available now – Access Private and Public Repo With User Permission.",
  },
  {
    title: "Phase 5: README Update Time",
    desc: "Coming Soon – After update Projects Repo Then Check whole Projects new functionality and Update Readme file.",
  },
];

export const faqList = [
  {
    question: "How can Readme Hub improve my GitHub profile to attract recruiters and boost my career?",
    answer: "GitDocify significantly enhances your GitHub profile by generating clear, professional, and comprehensive documentation for your projects.As companies increasingly shift away from traditional technical interviews—such as coding exercises on platforms like LeetCode—your project portfolio has become more critical than ever.By using GitDocify to document your projects, you clearly demonstrate your project's purpose, complexity, and value, making your GitHub portfolio stand out to recruiters and tech companies, greatly boosting your career prospects.",
  },
  {
    question: "How long does it take to generate a high-quality README with Readme Hub?",
    answer: "The time required to generate a high-quality README depends on the size and complexity of your codebase. GitDocify's AI agent thoroughly reviews each file in your repository to gather essential details, ensuring that the resulting documentation accurately reflects your project's depth and functionality.Typically, the process takes only a few minutes, even for large projects, delivering professional documentation swiftly and efficiently.",
  },
  {
    question: "Is my code protected and secure when using Readme Hub?",
    answer: "Yes, absolutely. GitDocify prioritizes the security and privacy of your code.We integrate directly with GitHub through a secure OAuth authentication, ensuring safe interactions with your repositories. We never store any of your code or data, and your codebase is never used to train our AI models.Your privacy and data security are guaranteed at all times.",
  },
  {
    question: "Can I customize the layout and style of my README generated by Readme Hub?",
    answer: "Yes! GitDocify offers robust customization options to match your personal or project branding.You can easily add specialized sections such as feature highlights, contribution guidelines, project indexes, logos, and much more.Additionally, you have full control over text styling, alignment, and formatting, enabling you to create visually appealing, distinctive, and professional READMEs tailored exactly to your needs.",
  },
  {
    question: "Which programming languages does Readme Hub support?",
    answer: "GitDocify supports ALL programming languages.Our advanced AI agent intelligently detects and comprehends every programming language, making it highly compatible not only with single-language projects but also complex multi-language codebases.Regardless of your stack, GitDocify will generate accurate and professional documentation seamlessly.",
  },
  {
    question: "How does Readme Hub’s AI analyze and review my code to create documentation?",
    answer: "GitDocify utilizes a powerful AI agent specifically trained to systematically analyze your entire codebase.It carefully collects detailed information such as dependencies, libraries, individual file functionality, project structure, and entry points.All gathered insights are synthesized into clear, concise, and well-structured documentation, ensuring that your projects are represented professionally and accurately.",
  },
];

export const termsData = {
  meta: {
    productName: "GitDocify",
    productShort: "Services",
    providerName: "GitDocify (unincorporated entity)",
    contactEmail: "support@gitdocify.com",
    minAge: 13,
    minorConsentNote:
      "If you are a minor (under the age of 18) in your jurisdiction, you must obtain parental or guardian consent and be directly supervised while using the Services.",
  },

  header: [
    {
      type: "paragraph",
      text:
        'Welcome to GitDocify ("Services"), a web-based platform dedicated to helping users generate structured code documentation for their code repositories. The Services are offered by the owner(s) of GitDocify, an unincorporated entity ("Provider" or "we"). By accessing or using our Services, you agree to comply with these Terms and Conditions ("Terms"). Please review them thoroughly before using the Services.',
    },
    {
      type: "warning",
      text:
        "IF YOU DO NOT AGREE WITH THESE TERMS, YOU ARE NOT AUTHORIZED TO USE THE SERVICES AND MUST CEASE USE IMMEDIATELY.",
    },
    {
      type: "paragraph",
      text:
        "The Services are intended for users aged 13 or older. If you are a minor (under the age of 18) in the jurisdiction where you reside, you must obtain parental or guardian consent and be directly supervised while using the Services. If you are a minor, your parent or guardian must read and accept these Terms on your behalf before you can use the Services. We recommend that you keep a copy of these Terms for your records.",
    },
  ] as ContentBlock[],

  sections: [
    {
      type: "section",
      title: "1. SERVICE AVAILABILITY & LIABILITY",
      blocks: [
        {
          type: "list",
          items: [
            "While we strive to make the Platform available at all times, we do not guarantee that it will be uninterrupted or error-free.",
            "We do not assume responsibility for any inaccuracies or errors in the content generated by our platform.",
            'Our platform is provided "as is" and we make no guarantees regarding its functionality or availability.',
            "In no event shall the Company be liable for any damages resulting from the use of the Platform.",
            "We reserve the right to update or discontinue our platform at any time without notice.",
          ],
        },
      ],
    },

    {
      type: "section",
      title: "2. INTELLECTUAL PROPERTY RIGHTS",
      blocks: [
        {
          type: "list",
          items: [
            'All content, features, and functionality available through the GitDocify platform, including but not limited to text, graphics, logos, images, software, and data compilations (collectively, "Platform Content"), are the exclusive property of GitDocify, its licensors, or other content providers, and are protected by applicable copyright, trademark, and other intellectual property laws.',
            "You may not copy, reproduce, distribute, display, transmit, modify, create derivative works from, or otherwise use any Platform Content without the prior written consent of GitDocify, except as permitted by applicable law or explicitly authorized by us.",
            "All trademarks, service marks, and trade names used on the platform (including GitDocify) are the property of GitDocify or their respective owners. Unauthorized use of any of these marks is strictly prohibited.",
            "GitDocify may incorporate open-source software components that are subject to their own license terms. By using the platform, you acknowledge that your use of any such third-party components is governed by the applicable third-party license(s).",
          ],
        },
      ],
    },

    {
      type: "section",
      title: "3. PRIVACY POLICY",
      blocks: [
        {
          type: "list",
          items: [
            "We take the protection of our users' personal information very seriously.",
            "Our privacy policy, which can be found on our website, explains how we collect, use, protect and disclose personal information.",
          ],
        },
      ],
    },

    {
      type: "section",
      title: "4. FREE TRIAL AND SUBSCRIPTIONS",
      blocks: [
        {
          type: "paragraph",
          text:
            "Free Trial: We offer a free trial that allows you to generate one (1) README with limited features. This trial does not include access to certain premium functionalities (such as private repository support, premium README sections, or copy/export options). Availability of the free trial and features provided may be subject to change at any moment.",
        },
        {
          type: "paragraph",
          text:
            "Once you have reached your free trial limit or wish to access additional features, you may upgrade to one of our paid subscription plans.",
        },
        {
          type: "sublist",
          title: "Subscription Plans",
          items: [
            "Monthly Plan: $14.95 per month, providing: Full access to private repositories, Premium README features, Up to 50 generations per month, and Copy/export options.",
            "Lifetime Plan: $54.99 (one-time payment), providing: Full access to private repositories, Premium README features, Up to 50 generations per month, Copy/export options, and Access to future feature updates at no additional charge.",
          ],
        },
        {
          type: "paragraph",
          text:
            "Payment Options: We accept various payment methods, including credit/debit cards and mobile payment options such as Apple Pay and Google Pay. All payments are processed securely through trusted third-party providers.",
        },
        {
          type: "paragraph",
          text:
            "Auto-Renewal: By subscribing to a Monthly Plan, you agree to pay the subscription fees indicated at the time of purchase. Your subscription will automatically renew at the end of each billing cycle unless you cancel before the renewal date. You may manage your subscription and disable auto-renewal at any time via your account settings. The Lifetime Plan is a one-time payment and does not renew.",
        },
        {
          type: "paragraph",
          text:
            "Cancellation and Refunds: You may cancel your Monthly Plan at any time through your account settings. Cancellations take effect at the end of the current billing cycle. No refunds will be provided for any remaining portion of the billing period following cancellation. All purchases, including the Lifetime Plan, are non-refundable once completed.",
        },
      ],
    },

    {
      type: "section",
      title: "5. DISCLAIMER OF WARRANTIES",
      blocks: [
        {
          type: "list",
          items: [
            'Services Provided "As Is": The Services are provided on an "as is" and "as available" basis. GitDocify and its licensors make no representations or warranties of any kind—express, implied, statutory, or otherwise—regarding the operation or availability of the Services, or the accuracy, reliability, completeness, or suitability of the information, content, materials, or products included on or generated by the platform.',
            "User Assumption of Risk: You expressly agree that your use of the Services is at your sole risk. To the fullest extent permissible under applicable law, GitDocify disclaims all warranties, whether express, implied, or statutory, including but not limited to any warranties of merchantability, fitness for a particular purpose, non-infringement, and error-free operation.",
            "No Guarantee of Uninterrupted or Error-Free Service: GitDocify does not guarantee that the Services will be secure, uninterrupted, error-free, or available at all times. We reserve the right to modify, suspend, or discontinue any aspect of the Services at any time, without notice or liability.",
            "Content and Accuracy: Any content generated, provided, or displayed via the Services is for informational purposes only. GitDocify does not warrant or guarantee the correctness, completeness, or usefulness of such content. You are solely responsible for verifying and evaluating the accuracy and suitability of any information or results obtained through the Services.",
            "Jurisdictional Limitations: Because some jurisdictions do not allow the exclusion of certain warranties, the above exclusions may not apply to you. In such jurisdictions, GitDocify's warranties shall be limited to the greatest extent permitted by law.",
          ],
        },
      ],
    },

    {
      type: "section",
      title: "6. LIMITATION OF LIABILITY",
      blocks: [
        {
          type: "list",
          items: [
            "To the fullest extent permitted by law, GitDocify and its licensors shall not be liable for any direct, indirect, incidental, punitive, or consequential damages, including but not limited to, damages for loss of profits, goodwill, data, or other intangible losses, arising out of or in connection with your use of the Services or any purchase, even if we have been advised of the possibility of such damages.",
            "In no event shall our total liability to you for all damages exceed the amount you paid, if any, for accessing the Services or purchases during the six (6) months preceding the event giving rise to the claim.",
          ],
        },
      ],
    },

    {
      type: "section",
      title: "7. CHANGES TO TERMS",
      blocks: [
        {
          type: "list",
          items: [
            "GitDocify reserves the right to modify or revise these Terms at any time, for any reason. The determination of what constitutes a material change will be at the sole discretion of GitDocify.",
            "By continuing to use the Services after such changes, you accept and agree to the updated Terms. If you do not agree to the revised Terms, you must cease using the Services immediately.",
          ],
        },
      ],
    },

    {
      type: "section",
      title: "8. CONTACT US",
      blocks: [
        {
          type: "paragraph",
          text:
            'If you have any questions or concerns regarding these terms of service, please contact us at support@gitdocify.com.',
        },
      ],
    },

    {
      type: "section",
      title: "USER POLICY",
      blocks: [
        {
          type: "list",
          items: [
            "Permissible Use: The GitDocify platform is provided for lawful and authorized use only. By accessing or using the Services, you agree to use the platform solely for legitimate, non-commercial, and recreational purposes, unless otherwise expressly permitted in writing by GitDocify.",
            "Prohibited Activities: You must not use the platform for any illegal, fraudulent, or unauthorized purposes, including but not limited to misuse, exploitation, or manipulation of the platform's features. We reserve the right to suspend, restrict, or terminate access to any account found to be in violation of these terms.",
            "Responsibility for Submitted Code and Content: You agree that you are solely responsible for any code, data, or other content you submit to or process through GitDocify. This includes ensuring you have all necessary permissions, licenses, or rights to use, upload, or modify such content, particularly if it is proprietary or protected (e.g., company-owned or confidential).",
            "By using GitDocify, you represent and warrant that your submission or processing of any code or content does not infringe upon any third party's rights, including intellectual property, trade secrets, or confidentiality obligations.",
            "GitDocify disclaims any liability arising from users' unauthorized use of code or content protected by law. We do not monitor or verify the ownership or legality of any submitted materials; you assume full responsibility for any claims, disputes, or damages resulting from your misuse or unauthorized use of such content.",
            "Enforcement: We reserve the right to investigate and take appropriate action—such as suspending, restricting, or terminating your account—if we believe you have violated this User Policy or any other applicable terms.",
          ],
        },
      ],
    },
  ] as { type: "section"; title: string; blocks: ContentBlock[] }[],
};

export type ContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "section"; title: string; blocks: ContentBlock[] }
  | { type: "list"; items: string[] }
  | { type: "sublist"; title?: string; items: string[] }
  | { type: "raw"; html: string };

export const privacyData = {
  meta: {
    productName: "GitDocify",
    contactEmail: "support@gitdocify.com",
  },

  header: [
    {
      type: "paragraph",
      text: `This Privacy Policy ("Policy") explains how GitDocify ("we," "us," or "our") collects, uses, discloses, and protects your
              personal data when you use our web application. By using the Application, you consent to the practices outlined in this Policy.
              If you disagree with the terms of this Policy, please refrain from using the platform.`,
    },
  ] as ContentBlock[],

  sections: [
    {
      type: "section",
      title: "INFORMATION WE COLLECT",
      blocks: [
        {
          type: "paragraph",
          text: "We collect various types of personal information depending on how you interact with the platform:",
        },
        {
          type: "raw",
          html: `<div className="mt-3">
                  <strong>GitHub Login Data:</strong>
                  <p className="mt-2">When you log in via your GitHub account, we may collect the following information from your GitHub profile, with your consent:</p>
                  <ul className="list-disc ml-6 mt-2 space-y-1">
                    <li>Name</li>
                    <li>Email address</li>
                    <li>Username</li>
                    <li>Profile Picture</li>
                  </ul>
                </div>`,
        },
      ],
    },

    {
      type: "section",
      title: "USE OF INFORMATION",
      blocks: [
        {
          type: "paragraph",
          text: "We may use the data we collect from you to:",
        },
        {
          type: "list",
          items: [
            "<strong>Provide and enhance the web application:</strong> We may use the data we collect to operate and maintain the web application, and to improve its features and functionality.",
            "<strong>Communicate with you:</strong> We may use the data we collect to send you updates about the platform and to respond to your inquiries and comments.",
            "<strong>Analyze and understand user behavior:</strong> We may use the data we collect to analyze and understand how users interact with the web application and to develop new features and functionality.",
            "<strong>Comply with legal obligations:</strong> We may use the data we collect to comply with any applicable laws, regulations, or legal requests.",
          ],
        },
        {
          type: "paragraph",
          text: "In addition, if you connect private repositories or submit code (including proprietary code) for generating documentation files, we use such code solely to provide the requested functionality. We do not permanently store or share this code with third parties beyond what is necessary to operate and maintain our Services.",
        },
      ],
    },

    {
      type: "section",
      title: "SHARING INFORMATION",
      blocks: [
        {
          type: "paragraph",
          text: "We do not share or transfer your personal information to any third parties except as described below, or in circumstances where you give consent:",
        },
        {
          type: "list",
          items: [
            "<strong>Public authorities:</strong> We may disclose your information to government, regulatory, judicial, or law enforcement bodies if required to comply with legal obligations, processes, or to protect security or prevent fraud.",
            "<strong>Service providers:</strong> We may share your data with service providers like data storage providers and payment processors who assist in providing the Services.",
            "<strong>Third-party integrations:</strong> If you allow third-party integrations (e.g., GitHub), we may share or retrieve data as part of those integrations.",
          ],
        },
        {
          type: "paragraph",
          text: "We do not sell personal information and have not done so in the past.",
        },
      ],
    },

    {
      type: "section",
      title: "THIRD-PARTY SERVICES",
      blocks: [
        {
          type: "paragraph",
          text: "We may utilize third-party services to facilitate certain features within the web application and our Services. These third-party platforms may provide us with data based on your interaction with their services, subject to your consent and their respective privacy policies. Specifically, we may collect information through the following platforms:",
        },
        {
          type: "list",
          items: [
            "<strong>GitHub Login:</strong> If you log in using your GitHub account, we may collect your name, email address, profile picture, and other basic profile information, with your permission.",
            "<strong>Tracking and Analytics:</strong> We may collect certain data automatically about your usage of the web application to improve functionality and user experience. This may include data such as your device type, IP address, browser type, and interactions with the app. We use tools such as Google Analytics to help us understand how users engage with our services. By using the web application, you consent to the collection of this data for these purposes. You may opt out of certain tracking by adjusting your device or browser settings.",
          ],
        },
        {
          type: "paragraph",
          text: "Please note that the information shared with these third-party services is governed by their respective privacy policies, and we recommend reviewing them to understand how your personal data is handled by these services.",
        },
      ],
    },

    {
      type: "section",
      title: "DATA RETENTION",
      blocks: [
        {
          type: "paragraph",
          text: "We will retain your personal data for as long as necessary to fulfill the purposes for which it was collected, as outlined in this Policy. We will also retain your personal data as required by applicable laws or regulations.",
        },
        {
          type: "paragraph",
          text: "<strong>Consent for Data Usage:</strong> By using the web application, you consent to the collection, use, and sharing of your data as described in this Privacy Policy. If we intend to use your data for additional purposes beyond those described, we will seek your explicit consent before doing so.",
        },
      ],
    },

    {
      type: "section",
      title: "YOUR DATA PROTECTION RIGHTS",
      blocks: [
        {
          type: "paragraph",
          text: "Depending on your location and applicable laws, you may have the following rights regarding your personal data:",
        },
        {
          type: "list",
          items: [
            "<strong>Access:</strong> You have the right to request access to the personal data we hold about you.",
            "<strong>Correction:</strong> You can correct any inaccuracies in your personal data.",
            "<strong>Deletion:</strong> You can request the deletion of your personal data (subject to certain legal exceptions).",
            "<strong>Objection or Restriction:</strong> You can object to or request the restriction of certain data processing activities.",
            "<strong>Data Portability:</strong> You can request to receive your personal data in a structured, machine-readable format and transmit it to another service provider.",
          ],
        },
        {
          type: "paragraph",
          text: `To exercise any of these rights, please contact us at <a className="text-blue-600 underline" href="mailto:support@gitdocify.com">support@gitdocify.com</a>. We will respond to your request in accordance with applicable data protection laws.`,
        },
      ],
    },

    {
      type: "section",
      title: "CHANGES TO THE POLICY",
      blocks: [
        {
          type: "paragraph",
          text: "We may update this Policy from time to time to reflect changes in our data practices or for other operational, legal, or regulatory reasons. When we update this Policy, we will notify you through the web application or by other means. Your continued use of the web application after any changes constitutes your acceptance of the updated Policy.",
        },
      ],
    },

    {
      type: "section",
      title: "CONTACT INFORMATION",
      blocks: [
        {
          type: "paragraph",
          text: `If you have any questions or concerns regarding this Privacy Policy or our data practices, please contact us at: <a className="text-blue-600 underline" href="mailto:support@gitdocify.com">support@gitdocify.com</a>.`,
        },
      ],
    },
  ] as { type: "section"; title: string; blocks: ContentBlock[] }[],
};

export default privacyData;